spin_version = "1"
authors = ["Douglas A <andreani.dr@gmail.com>"]
description = ""
name = "wasm-bench"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "wasm-bench"
source = "target/wasm32-wasi/release/wasm_bench.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
